use_frameworks!

platform :ios, '8.0'

target 'YHOCMonkey_Example' do
  pod 'YHOCMonkey', :path => '../'

  target 'YHOCMonkey_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
