# use_frameworks!

platform :ios, '8.0'

target 'YHOCMonkey_Example' do
  pod 'YHOCMonkey/Paws', :path => '../'

  target 'YHOCMonkey_ExampleUITests' do
    inherit! :search_paths
    pod 'YHOCMonkey/Test', :path => '../'
  end
end
